export const SERVER_ERROR = 'SERVER_ERROR';
export const DROP_DOES_NOT_EXIST = 'DROP_DOES_NOT_EXIST';
export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const INVALID_DATA = 'INVALID_DATA';
export const BROWSER_NOT_SUPPORTED = 'BROWSER_NOT_SUPPORTED';